[book]
    authors = ["TrueBlocks, LLC"]
    language = "en"
    multilingual = false
    src = "src"
    title = "The Khedra Book"

[output.html]
    numbered = false
    default-theme = "rust"
    theme = "theme"
    additional-js = ["theme/build-info.js"]

[preprocessor.mermaid]

